# Generated by Django 4.1.2 on 2022-10-21 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="date",
            field=models.DateField(default="2022-10-21"),
            preserve_default=False,
        ),
    ]
