# Generated by Django 4.1.2 on 2022-10-22 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0002_tournament_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="is_complete",
            field=models.BooleanField(blank=True),
        ),
    ]
