# Generated by Django 4.1.2 on 2022-10-23 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0006_player_host"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="players",
            field=models.ManyToManyField(to="main_app.player"),
        ),
    ]
