# Generated by Django 4.1.2 on 2022-10-24 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0007_tournament_players"),
    ]

    operations = [
        migrations.RemoveField(model_name="tournament", name="user",),
        migrations.AddField(
            model_name="tournament",
            name="host",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="main_app.host",
            ),
            preserve_default=False,
        ),
    ]
