# Generated by Django 4.1.2 on 2022-10-24 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main_app", "0008_remove_tournament_user_tournament_host"),
    ]

    operations = [
        migrations.RemoveField(model_name="tournament", name="host",),
        migrations.AddField(
            model_name="tournament",
            name="user",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
